### ISSUE TITLE
Error in client area

### ISSUE THREAD

**Issue by WaldperlachFabi** [The-Network-Crew/Proxmox-VE-for-WHMCS#15]
I get this error in my client area:

DivisionByZeroError: Division by zero in /var/www/vhosts/web8209.web07.bero-webspace.de/cp.waldperlachfabi.de/whmcs/modules/servers/pvewhmcs/pvewhmcs.php:501
Stack trace:
#0 [internal function]: pvewhmcs_ClientArea()
#1 /var/www/vhosts/web8209.web07.bero-webspace.de/cp.waldperlachfabi.de/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func()
#2 /var/www/vhosts/web8209.web07.bero-webspace.de/cp.waldperlachfabi.de/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/Server.php(0): WHMCS\Module\AbstractModule->call()
#3 /var/www/vhosts/web8209.web07.bero-webspace.de/cp.waldperlachfabi.de/whmcs/vendor/whmcs/whmcs-foundation/lib/Service.php(0): WHMCS\Module\Server->call()
#4 /var/www/vhosts/web8209.web07.bero-webspace.de/cp.waldperlachfabi.de/whmcs/clientarea.php(0): WHMCS\Service->moduleCall()
#5 {main}

**Comment by lsthompson** [comment]
This relates to Issue #13

Are you sure it's connecting to PVE okay? Please check Proxmox's logs.

Can you confirm any functions in the module that are working properly? ie. VM/CT creation.
